name: pymuse
channels:
  - conda-forge
  - astropy
  - defaults
dependencies:
  - python>=3.7
  - pip
  - astropy
  - astroquery
  - corner
  - dust_extinction
  - emcee
  - numpy
  - photutils
  - scipy
  - speclite
  - spectral-cube
  - pandas
  - ipython
  - matplotlib
  - pip:
  # add here only pip-packages that are not available in conda/conda-forge! E.g.:
  # for development only (could also be kept in a separate environment file)
  - jupyterlab
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark
